# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master, dev, actions ]
  pull_request:
    branches: [ master, dev, actions ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      ui-dir: ./forseti-visualizer-ui
      api-dir: ./forseti-api

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      working-directory: ./forseti-visualizer-ui
      run: npm install
    - name: Run Build
      working-directory: ./forseti-visualizer-ui
      run: npm run build --if-present
    - name: Run Test
      working-directory: ./forseti-visualizer-ui
      run: npm test
    - name: Install Packaages
      working-directory: ./forseti-api
      run: npm install
    - name: Run Build
      working-directory: ./forseti-api
      run: npm run build --if-present
    - name: Run Test
      working-directory: ./forseti-api 
      run: npm test
