# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: 2019-02-28T21:41:16Z
  generation: 2
  labels:
    run: forsetiapi
  name: forsetiapi
  namespace: default
  resourceVersion: "226146"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/forsetiapi
  uid: 93e06eb3-3ba1-11e9-a193-42010a80019c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: forsetiapi
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: forsetiapi
    spec:
      containers:
      - env:
        - name: CLOUDSQL_HOSTNAME
          value: 35.202.235.239
        - name: CLOUDSQL_USERNAME
          value: forseti
        - name: CLOUDSQL_PASSWORD
          value: testPassword1
        - name: CLOUDSQL_SCHEMA
          value: forseti_security
        - name: FORSETI_SERVER_VM_CHANNEL
          value: 35.189.28.28:50051
        - name: FORSETI_DATA_MODEL_HANDLE
        image: gcr.io/australia-hack-6-7dc4/forsetiapi:v2
        imagePullPolicy: Always
        name: forsetiapi
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2019-02-28T21:43:11Z
    lastUpdateTime: 2019-02-28T21:43:11Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2019-02-28T21:41:16Z
    lastUpdateTime: 2019-02-28T21:56:46Z
    message: ReplicaSet "forsetiapi-6bcc46c5d9" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
